language: node_js
node_js:
  - 6
install:
  - npm install
script:
  - npm run autostart
  - npm test
notifications:
  webhooks:
    urls:
      - https://api.kratelabs.addxy.com/github
    on_success: always
    on_failure: never
    on_start: never
  email:
    - carriere.denis@gmail.com
