api:
  restart: always
  build: .
  environment:
    - PORT=5000
    - MONGODB=mongodb://kratelabs:kratelabs@ds013414.mlab.com:13414/kratelabs
    - SECRET=default
  expose:
    - 5000
  ports:
    - 5000:5000
