web:
  restart: always
  build: ./web
  expose:
    - 5000
  links:
    - redis:redis
  command: gunicorn -w 4 -b :5000 app:app

nginx:
  restart: always
  image: nginx:alpine
  volumes:
    - ./nginx:/etc/nginx
  ports:
    - 80:80
    - 443:443
  links:
    - web:web

redis:
  restart: always
  image: redis:alpine
  expose:
    - 6379
