web:
  restart: always
  build: ./web
  expose:
    - 5000
  ports:
    - 5000:5000
  links:
     - redis:redis
  command: gunicorn -w 4 -b :5000 app:app

nginx:
  restart: always
  build: ./nginx
  ports:
    - 80:80
  links:
    - web:web

redis:
  restart: always
  image: redis:alpine
  ports:
    - 6379:6379
